steps:
- name: 'bash'
  args: ['ls -al']

- name: 'bash'
  args: ['./Xponents/script/dist.sh']

- name: 'bash'
  args: ['./Xponents/script/dist-docker.sh']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/apt-gear-288208/xponents', './Xponents/dist/Xponents-*']